### ISSUE TITLE
Issue checking file

### ISSUE THREAD

**Issue by thomas-lamiaux** [coq/platform-docs#48]
There seem to be an issue with the docker image checking files which may be a bit too old due to web interface as as you can see it bug on a the type scope 
```
   (nat + bool)%type
       : Set
  File "./SearchTutorial.v", line 191, characters 0-19:
  Error: Error: Scope type is not declared.
```
https://github.com/coq/platform-docs/actions/runs/10952451667/job/30411152058?pr=9#step:4:4624

**Comment by thomas-lamiaux** [comment]
coq/platform-docs-admins I suggest switching docker to 8.19 as it is the platform version so that it always work with the current version when downloaded, even if the web version bugs at the moment

**Comment by Zimmi48** [comment]
> I suggest switching docker to 8.19

OK to me.

Note that you forgot a `@` to properly mention the team.
