### ISSUE TITLE
Can't run Search tutorial

### ISSUE THREAD

**Issue by Lysxia** [coq/platform-docs#67]
On Coq 8.20, the following command from the tutorial fails:

```coq
About "_ + _"%type.
(*
File "./SearchTutorial.v", line 191, characters 0-19:
Error: Scope type is not declared.
*)
```

**Comment by thomas-lamiaux** [comment]
This normal the version supported is 8.19 not 8.20.  
I have updated the readme and the web page to make this clearer.
